name: MacOS

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  BUILD_TYPE: Release

jobs:
  cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS Clang Default
            os: macos-latest
            compiler: clang
            cxx-compiler: clang++
            cmake-args: ""
            coverage: macos_clang

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        export CC=${{ matrix.compiler }}
        export CXX=${{ matrix.cxx-compiler }}
        cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} \
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
              ${{ matrix.cmake-args }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
