name: Ubuntu

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  BUILD_TYPE: Debug

jobs:
  cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 80
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu GCC Default
            os: ubuntu-latest
            compiler: gcc
            cxx-compiler: g++
            cmake-args: ""
            coverage: ubuntu_gcc

          - name: Ubuntu Clang Default
            os: ubuntu-latest
            compiler: clang
            cxx-compiler: clang++
            cmake-args: ""
            coverage: ubuntu_clang

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential clang

    - name: Configure CMake
      run: |
        export CC=${{ matrix.compiler }}
        export CXX=${{ matrix.cxx-compiler }}
        cmake -B ${{ github.workspace }}/build \
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
              ${{ matrix.cmake-args }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure